version: '3.7'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000"
    environment:
      - POSTGRES_URL=postgres://user:password@postgres:5432/authdb
      - REDIS_URL=redis://redis:6379
  booking-service:
    build: ./booking-service
    ports:
      - "3002:3000"
    environment:
      - POSTGRES_URL=postgres://user:password@postgres:5432/bookingdb
      - REDIS_URL=redis://redis:6379
  payment-service:
    build: ./payment-service
    ports:
      - "3003:3000"
    environment:
      - POSTGRES_URL=postgres://user:password@postgres:5432/paymentdb
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres-data:
